version: '3'

services:

  laravel:
    build:
      context: ./docker/
      dockerfile: laravel.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/usr/share/nginx/html:cached
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  redis_vnu:
    image: 'bitnami/redis:latest'
    container_name: redis_vnu
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENABLE_OVERCOMMIT_MEMORY=true
    ports:
      - ${REDIS_PORT_EXTERNAL}:6379
    volumes:
      - ./redis_data:/bitnami/redis/data
    restart: always

  http-nginx:
    image: nginx:1.14.2-alpine
    ports:
      - "9000:80"
      - "444:443"
    volumes:
      - ./docker/http-nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/usr/share/nginx/html:cached
      - ./docker/cert:/etc/nginx/cert
    links:
      - laravel
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker:/etc/mysql/conf.d
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./mysqldata:/var/lib/mysql
